AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - 'vendor/**/*'
    - 'lib/helpers/*.rb'

Rails:
  Enabled: true

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Style/ClassAndModuleChildren:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'

Rails/Output:
  Exclude:
    - 'db/*.rb'
    - 'db/seeds/*.rb'
