require Rails.root.join('lib', 'watson')
require Rails.root.join('lib', 'psychonaut')
require Rails.root.join('lib', 'errors')
require Rails.root.join('lib', 'tripsit')
require Rails.root.join('lib', 'recast')
require Rails.root.join('lib', 'helpers', 'indefinite_article')
