class CreateSubstances < ActiveRecord::Migration[5.0]
  def change
    create_table :substances do |t|
       t.string :name
       t.string :alternate_name
       t.string :addiction_potential
       t.string :chemical_class
       t.string :cross_tolerance
       t.string :dangerous_interactions
       t.text :effects
       t.string :insufflated_afterglow_time_units
       t.string :insufflated_comeup_time_units
       t.string :insufflated_dose_units
       t.string :insufflated_heavy_dose
       t.string :insufflated_max_afterglow_time
       t.string :insufflated_max_bioavailability
       t.string :insufflated_max_comeup_time
       t.string :insufflated_max_common_dose
       t.string :insufflated_max_light_dose
       t.string :insufflated_max_offset_time
       t.string :insufflated_max_onset_time
       t.string :insufflated_max_peak_time
       t.string :insufflated_max_strong_dose
       t.string :insufflated_max_total_time
       t.string :insufflated_min_afterglow_time
       t.string :insufflated_min_bioavailability
       t.string :insufflated_min_comeup_time
       t.string :insufflated_min_common_dose
       t.string :insufflated_min_light_dose
       t.string :insufflated_min_offset_time
       t.string :insufflated_min_onset_time
       t.string :insufflated_min_peak_time
       t.string :insufflated_min_strong_dose
       t.string :insufflated_min_total_time
       t.string :insufflated_offset_time_units
       t.string :insufflated_onset_time_units
       t.string :insufflated_peak_time_units
       t.string :insufflated_threshold_dose
       t.string :insufflated_total_time_units
       t.string :intravenous_afterglow_time_units
       t.string :intravenous_comeup_time_units
       t.string :intravenous_dose_units
       t.string :intravenous_heavy_dose
       t.string :intravenous_max_afterglow_time
       t.string :intravenous_max_bioavailability
       t.string :intravenous_max_comeup_time
       t.string :intravenous_max_common_dose
       t.string :intravenous_max_light_dose
       t.string :intravenous_max_offset_time
       t.string :intravenous_max_onset_time
       t.string :intravenous_max_peak_time
       t.string :intravenous_max_strong_dose
       t.string :intravenous_max_total_time
       t.string :intravenous_min_afterglow_time
       t.string :intravenous_min_bioavailability
       t.string :intravenous_min_comeup_time
       t.string :intravenous_min_common_dose
       t.string :intravenous_min_light_dose
       t.string :intravenous_min_offset_time
       t.string :intravenous_min_onset_time
       t.string :intravenous_min_peak_time
       t.string :intravenous_min_strong_dose
       t.string :intravenous_min_total_time
       t.string :intravenous_offset_time_units
       t.string :intravenous_onset_time_units
       t.string :intravenous_peak_time_units
       t.string :intravenous_threshold_dose
       t.string :intravenous_total_time_units
       t.string :oral_afterglow_time_units
       t.string :oral_comeup_time_units
       t.string :oral_dose_units
       t.string :oral_heavy_dose
       t.string :oral_max_afterglow_time
       t.string :oral_max_bioavailability
       t.string :oral_max_comeup_time
       t.string :oral_max_common_dose
       t.string :oral_max_light_dose
       t.string :oral_max_offset_time
       t.string :oral_max_onset_time
       t.string :oral_max_peak_time
       t.string :oral_max_strong_dose
       t.string :oral_max_total_time
       t.string :oral_min_afterglow_time
       t.string :oral_min_bioavailability
       t.string :oral_min_comeup_time
       t.string :oral_min_common_dose
       t.string :oral_min_light_dose
       t.string :oral_min_offset_time
       t.string :oral_min_onset_time
       t.string :oral_min_peak_time
       t.string :oral_min_strong_dose
       t.string :oral_min_total_time
       t.string :oral_offset_time_units
       t.string :oral_onset_time_units
       t.string :oral_peak_time_units
       t.string :oral_threshold_dose
       t.string :oral_total_time_units
       t.string :psychoactive_class
       t.string :sublingual_afterglow_time_units
       t.string :sublingual_comeup_time_units
       t.string :sublingual_dose_units
       t.string :sublingual_heavy_dose
       t.string :sublingual_max_afterglow_time
       t.string :sublingual_max_bioavailability
       t.string :sublingual_max_comeup_time
       t.string :sublingual_max_common_dose
       t.string :sublingual_max_light_dose
       t.string :sublingual_max_offset_time
       t.string :sublingual_max_onset_time
       t.string :sublingual_max_peak_time
       t.string :sublingual_max_strong_dose
       t.string :sublingual_max_total_time
       t.string :sublingual_min_afterglow_time
       t.string :sublingual_min_bioavailability
       t.string :sublingual_min_comeup_time
       t.string :sublingual_min_common_dose
       t.string :sublingual_min_light_dose
       t.string :sublingual_min_offset_time
       t.string :sublingual_min_onset_time
       t.string :sublingual_min_peak_time
       t.string :sublingual_min_strong_dose
       t.string :sublingual_min_total_time
       t.string :sublingual_offset_time_units
       t.string :sublingual_onset_time_units
       t.string :sublingual_peak_time_units
       t.string :sublingual_threshold_dose
       t.string :sublingual_total_time_units
       t.string :smoked_afterglow_time_units
       t.string :smoked_comeup_time_units
       t.string :smoked_dose_units
       t.string :smoked_heavy_dose
       t.string :smoked_max_afterglow_time
       t.string :smoked_max_bioavailability
       t.string :smoked_max_comeup_time
       t.string :smoked_max_common_dose
       t.string :smoked_max_light_dose
       t.string :smoked_max_offset_time
       t.string :smoked_max_onset_time
       t.string :smoked_max_peak_time
       t.string :smoked_max_strong_dose
       t.string :smoked_max_total_time
       t.string :smoked_min_afterglow_time
       t.string :smoked_min_bioavailability
       t.string :smoked_min_comeup_time
       t.string :smoked_min_common_dose
       t.string :smoked_min_light_dose
       t.string :smoked_min_offset_time
       t.string :smoked_min_onset_time
       t.string :smoked_min_peak_time
       t.string :smoked_min_strong_dose
       t.string :smoked_min_total_time
       t.string :smoked_offset_time_units
       t.string :smoked_onset_time_units
       t.string :smoked_peak_time_units
       t.string :smoked_threshold_dose
       t.string :smoked_total_time_units
       t.string :time_to_full_tolerance
       t.string :time_to_half_tolerance
       t.string :time_to_zero_tolerance
       t.string :toxicity
       t.jsonb :full_response
       t.timestamps
    end
  end
end
